### ISSUE TITLE
Telegram Bot not working

### ISSUE THREAD

**Issue by 8acoustic** [bugsounet/MMM-Tools#35]
showing "You can't send commands, contact admin"
help me pls.

**Comment by eouia** [comment]
More details be needed. Which commands did you try? All commands are not working?

**Comment by 8acoustic** [comment]
yes all of them

**Comment by bugsounet** [comment]
native function of TelegramBot works ?

**Comment by 8acoustic** [comment]
yea
all of them

**Comment by bugsounet** [comment]
so, what function doesn't work ?
can you explain?
I need more information ...
because native fonction is not related to this module
