### ISSUE TITLE
MMM-Tools

### ISSUE THREAD

**Issue by MiPraSo** [bugsounet/MMM-Tools#44]
Hello,

I have been using your MMM-Tools module for the Magic Mirror for some time now. At the moment the output of the GPU temperature does not work with the current OS, because the file for the readout is no longer available. No problem, that is not important.

I tried to display both IP addresses of the network controllers, eth0 and wlan0, the readout is no problem, but I have a problem with displaying it. I have no JavaScript experience, I hate it! I like Delphi, Pascal, ASM and Kotlin.

I have already adjusted some things:
1. The MAC address of the LAN is now displayed as eth0 again. 
2. I can read out both IP addresses via script and store them in varibales.
What I can't do is the display. My goal is to create what is written there:
IP: LAN: 192.186.1.xx, WiFi: 192.186.1.xx

If you are interested, I can send you my attempts.
A german version de.json I have here.

Greeting,
Michael

Translated with www.DeepL.com/Translator (free version)

**Comment by bugsounet** [comment]
It will be available soon with MMM-Tool v2

I'm actually refact all code (in dev branch) and will add some new features :) 

just wait and i will be back to you when it's done

**Comment by MiPraSo** [comment]
Good work, thank you very much.

**Comment by bugsounet** [comment]
I finalize v2, I think it's ready for release :)

**Comment by bugsounet** [comment]
news is [there](https://github.com/bugsounet/MMM-Tools/tree/dev#mmm-tools)
