### ISSUE TITLE
Update dom at start if hidden

### ISSUE THREAD

**Issue by Snille** [bugsounet/MMM-Tools#60]
Hi! Thanks for this module, I've been using it for quite some time. :)
I have my mirror setup with many different profiles and when the mirror starts, almost all modules are "hidden" by default. So is this module. However, it shows itself when it updates for the first time, even if it set to hidden.
If I then "hide" the module, it stays hidden until it is shown again as it should. It's just at start, it is misbehaving. :)

**Comment by bugsounet** [comment]
Hi, effectivelely, it's start in hidden mode
why ?
The first time, it take all value to make autosizing. (Forced by the module and locked)

maybe you can try this : 
You can override autosizing with set in your config:
`containerSize` and `itemSize`
see description in [structure of the config](https://github.com/bugsounet/MMM-Tools/wiki/Configuration-Structure#field-in-root)

if you define this 2 features, the module wiil do this:
Force the value in px defined and so no hidden is needed for calculating sizing of the module (forced by config)
i think sould be correct your issue

**Comment by Snille** [comment]
Thank you! It worked! :)
